language: php
php:
  - '7.2'
cache: yarn
before_script:
  - curl -s http://getcomposer.org/installer | php
  - cd oekaki; php composer.phar install --prefer-source; cd ..
script:
  - yarn build
  ssh_known_hosts:
    - dragonoid.sakura.ne.jp
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r $TRAVIS_BUILD_DIR/ $SSH_USER@dragonoid.sakura.ne.jp:$DEPLOY_PATH
  on:
    branch: master
before_deploy:
  - openssl aes-256-cbc -K $encrypted_943504017263_key -iv $encrypted_943504017263_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
