language: php
php:
  - '7.1'
cache: yarn
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source
script:
  - mkdir -p build/logs
after_script:
  - php vendor/bin/coveralls -v
addons:
  ssh_known_hosts:
    - $DEPLOY_HOST
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r $TRAVIS_BUILD_DIR $SSH_USER:$DEPLOY_PASSWORD@$DEPLOY_HOST:$DEPLOY_PATH
  on:
    branch: master
before_deploy:
  - openssl aes-256-cbc -K $encrypted_943504017263_key -iv $encrypted_943504017263_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
